<?php

return [
    /*
     * Role-neutral panel manifest. Visibility is resolved from effective
     * permissions and scopes, not from hardcoded role names or panel folders.
     */
    'modules' => [
        [
            'id' => 'dashboard',
            'panel_type' => 'authority',
            'label' => 'Dashboard',
            'section' => 'overview',
            'href' => '/panel',
            'icon' => 'layout-dashboard',
            'order' => 10,
            'view_permissions' => [
                'dashboard.admin.view',
                'dashboard.coordinator.view',
                'dashboard.staff.view',
            ],
            'actions' => [
                'dashboard.admin.view',
                'dashboard.coordinator.view',
                'dashboard.staff.view',
            ],
        ],
        [
            'id' => 'projects',
            'panel_type' => 'authority',
            'label' => 'Projeler',
            'section' => 'projects',
            'href' => '/panel/projects',
            'icon' => 'folder-kanban',
            'order' => 20,
            'view_permissions' => ['projects.view'],
            'actions' => [
                'projects.view',
                'projects.export',
                'projects.content.update',
                'projects.gallery.update',
                'projects.application_form.update',
                'projects.participants.view',
                'projects.participants.manage',
                'projects.alumni.view',
                'projects.student_cv.view',
            ],
        ],
        [
            'id' => 'participants',
            'panel_type' => 'authority',
            'label' => 'Katilimci Ozet',
            'section' => 'projects',
            'href' => '/panel/participants',
            'icon' => 'users',
            'order' => 25,
            'view_permissions' => ['projects.participants.view'],
            'actions' => [
                'projects.participants.view',
                'projects.participants.manage',
                'projects.alumni.view',
                'projects.student_cv.view',
            ],
        ],
        [
            'id' => 'my_project',
            'panel_type' => 'authority',
            'label' => 'Projem',
            'section' => 'projects',
            'href' => '/panel/my-project',
            'icon' => 'briefcase-business',
            'order' => 26,
            'view_permissions' => ['projects.view'],
            'actions' => ['projects.view', 'projects.content.update', 'projects.gallery.update'],
        ],
        [
            'id' => 'periods',
            'panel_type' => 'authority',
            'label' => 'Donemler',
            'section' => 'projects',
            'href' => '/panel/periods',
            'icon' => 'calendar-range',
            'order' => 30,
            'view_permissions' => ['periods.view'],
            'actions' => ['periods.view', 'periods.create', 'periods.update', 'periods.export'],
        ],
        [
            'id' => 'programs',
            'panel_type' => 'authority',
            'label' => 'Programlar',
            'section' => 'projects',
            'href' => '/panel/programs',
            'icon' => 'calendar-days',
            'order' => 40,
            'view_permissions' => ['programs.view'],
            'actions' => [
                'programs.view',
                'programs.attendance.view',
                'programs.attendance.manage',
                'programs.attendance.export',
                'programs.create',
                'programs.update',
                'programs.media.upload',
                'programs.complete',
                'programs.qr.manage',
                'programs.export',
            ],
        ],
        [
            'id' => 'calendar',
            'panel_type' => 'authority',
            'label' => 'Takvim',
            'section' => 'projects',
            'href' => '/panel/calendar',
            'icon' => 'calendar',
            'order' => 50,
            'view_permissions' => ['calendar.view'],
            'actions' => [
                'calendar.view',
                'calendar.export',
                'calendar.assignments.manage',
                'calendar.meetings.create',
                'calendar.meetings.manage',
                'calendar.google.connect',
                'calendar.google.sync',
            ],
        ],
        [
            'id' => 'applications',
            'panel_type' => 'authority',
            'label' => 'Basvurular',
            'section' => 'operations',
            'href' => '/panel/applications',
            'icon' => 'clipboard-list',
            'order' => 60,
            'view_permissions' => ['applications.view'],
            'actions' => [
                'applications.view',
                'applications.update_status',
                'applications.plan_interview',
                'applications.waitlist.manage',
                'applications.export',
            ],
        ],
        [
            'id' => 'volunteer',
            'panel_type' => 'authority',
            'label' => 'Gonulluluk',
            'section' => 'operations',
            'href' => '/panel/volunteer',
            'icon' => 'heart-handshake',
            'order' => 70,
            'view_permissions' => ['volunteer.view'],
            'actions' => ['volunteer.view', 'volunteer.manage'],
        ],
        [
            'id' => 'financials',
            'panel_type' => 'authority',
            'label' => 'Mali Islemler',
            'section' => 'operations',
            'href' => '/panel/financials',
            'icon' => 'wallet',
            'order' => 80,
            'view_permissions' => ['financial.view'],
            'actions' => [
                'financial.view',
                'financial.create',
                'financial.update',
                'financial.delete',
                'financial.approve',
                'financial.reject',
                'financial.mark_paid',
                'financial.export',
                'financial.invoice.download',
            ],
        ],
        [
            'id' => 'requests',
            'panel_type' => 'authority',
            'label' => 'Talepler',
            'section' => 'operations',
            'href' => '/panel/requests',
            'icon' => 'inbox',
            'order' => 90,
            'view_permissions' => ['requests.view'],
            'actions' => [
                'requests.view',
                'requests.create',
                'requests.update_status',
                'requests.upload_response',
                'requests.export',
            ],
        ],
        [
            'id' => 'support',
            'panel_type' => 'authority',
            'label' => 'Destek',
            'section' => 'operations',
            'href' => '/panel/support',
            'icon' => 'life-buoy',
            'order' => 100,
            'view_permissions' => ['support.view'],
            'actions' => ['support.view', 'support.create', 'support.assign', 'support.reply', 'support.close', 'support.export'],
        ],
        [
            'id' => 'assignments',
            'panel_type' => 'authority',
            'label' => 'Odevler',
            'section' => 'projects',
            'href' => '/panel/assignments',
            'icon' => 'file-check',
            'order' => 110,
            'view_permissions' => ['assignments.view'],
            'actions' => [
                'assignments.view',
                'assignments.create',
                'assignments.delete',
                'assignments.submissions.view',
                'assignments.submissions.review',
            ],
        ],
        [
            'id' => 'digital_bohca',
            'panel_type' => 'authority',
            'label' => 'Dijital Bohca',
            'section' => 'projects',
            'href' => '/panel/digital-bohca',
            'icon' => 'archive',
            'order' => 120,
            'view_permissions' => ['digital_bohca.view'],
            'actions' => ['digital_bohca.view', 'digital_bohca.create', 'digital_bohca.delete'],
        ],
        [
            'id' => 'certificates',
            'panel_type' => 'authority',
            'label' => 'Sertifikalar',
            'section' => 'operations',
            'href' => '/panel/certificates',
            'icon' => 'badge-check',
            'order' => 130,
            'view_permissions' => ['certificates.view'],
            'actions' => ['certificates.view', 'certificates.create', 'certificates.delete', 'certificates.export'],
        ],
        [
            'id' => 'announcements',
            'panel_type' => 'authority',
            'label' => 'Duyurular',
            'section' => 'communication',
            'href' => '/panel/announcements',
            'icon' => 'megaphone',
            'order' => 140,
            'view_permissions' => ['announcements.view'],
            'actions' => [
                'announcements.view',
                'announcements.create',
                'announcements.update',
                'announcements.delete',
                'announcements.export',
                'announcements.send_sms',
                'announcements.send_email',
            ],
        ],
        [
            'id' => 'content',
            'panel_type' => 'authority',
            'label' => 'Icerik',
            'section' => 'communication',
            'href' => '/panel/content',
            'icon' => 'newspaper',
            'order' => 150,
            'view_permissions' => ['content.view'],
            'actions' => [
                'content.view',
                'content.blog.create',
                'content.blog.update',
                'content.blog.delete',
                'content.blog.export',
                'content.faq.create',
                'content.faq.update',
                'content.faq.delete',
                'content.faq.export',
                'content.site_settings.update',
                'content.personality.view',
                'content.personality.manage',
                'motivation.view',
                'motivation.manage',
            ],
        ],
        [
            'id' => 'staff',
            'panel_type' => 'authority',
            'label' => 'Personel',
            'section' => 'people',
            'href' => '/panel/staff',
            'icon' => 'users',
            'order' => 160,
            'view_permissions' => ['staff.view'],
            'actions' => [
                'staff.view',
                'staff.update',
                'staff.documents.upload',
                'staff.leave.request',
                'staff.leave.approve',
                'staff.leave.reject',
                'staff.export',
            ],
        ],
        [
            'id' => 'members',
            'panel_type' => 'authority',
            'label' => 'Birim Uyeleri',
            'section' => 'people',
            'href' => '/panel/members',
            'icon' => 'users',
            'order' => 165,
            'view_permissions' => ['staff.view'],
            'actions' => ['staff.view', 'staff.export'],
        ],
        [
            'id' => 'users',
            'panel_type' => 'authority',
            'label' => 'Kullanicilar',
            'section' => 'system',
            'href' => '/panel/users',
            'icon' => 'user-cog',
            'order' => 170,
            'view_permissions' => ['users.view'],
            'actions' => ['users.view', 'users.create', 'users.update', 'users.delete', 'users.export', 'users.assign_role'],
        ],
        [
            'id' => 'permission_matrix',
            'panel_type' => 'authority',
            'label' => 'Yetki Matrisi',
            'section' => 'system',
            'href' => '/panel/users/permissions',
            'icon' => 'shield-check',
            'order' => 180,
            'view_permissions' => ['permissions.matrix.view'],
            'actions' => [
                'permissions.matrix.view',
                'permissions.matrix.update',
                'permissions.user_override.view',
                'permissions.user_override.update',
            ],
        ],
        [
            'id' => 'settings',
            'panel_type' => 'authority',
            'label' => 'Ayarlar',
            'section' => 'system',
            'href' => '/panel/settings',
            'icon' => 'settings',
            'order' => 190,
            'view_permissions' => ['settings.view'],
            'actions' => ['settings.view', 'settings.update'],
        ],
        [
            'id' => 'logs',
            'panel_type' => 'authority',
            'label' => 'Loglar',
            'section' => 'system',
            'href' => '/panel/logs',
            'icon' => 'list-checks',
            'order' => 200,
            'view_permissions' => ['logs.view'],
            'actions' => ['logs.view', 'logs.export'],
        ],
        [
            'id' => 'newsletter',
            'panel_type' => 'authority',
            'label' => 'E-Bulten',
            'section' => 'communication',
            'href' => '/panel/newsletter',
            'icon' => 'mail',
            'order' => 210,
            'view_permissions' => ['newsletter.view'],
            'actions' => ['newsletter.view', 'newsletter.export', 'newsletter.manage'],
        ],
        [
            'id' => 'chatbot',
            'panel_type' => 'authority',
            'label' => 'Chatbot',
            'section' => 'system',
            'href' => '/panel/chatbot',
            'icon' => 'bot',
            'order' => 220,
            'view_permissions' => ['chatbot.view'],
            'actions' => ['chatbot.view', 'chatbot.manage'],
        ],
        [
            'id' => 'kpd',
            'panel_type' => 'authority',
            'label' => 'KPD',
            'section' => 'operations',
            'href' => '/panel/kpd',
            'icon' => 'stethoscope',
            'order' => 230,
            'view_permissions' => ['kpd.appointments.view'],
            'actions' => [
                'kpd.appointments.view',
                'kpd.appointments.manage',
                'kpd.reports.view',
                'kpd.reports.create',
                'kpd.reports.delete',
            ],
        ],
        [
            'id' => 'inbox',
            'panel_type' => 'authority',
            'label' => 'Mesaj Kutusu',
            'section' => 'communication',
            'href' => '/panel/inbox',
            'icon' => 'mail',
            'order' => 240,
            'view_permissions' => ['announcements.view'],
            'actions' => ['announcements.view'],
        ],
        [
            'id' => 'alumni_opportunities_panel',
            'panel_type' => 'authority',
            'label' => 'Kariyer Firsatlari',
            'section' => 'communication',
            'href' => '/panel/alumni-opportunities',
            'icon' => 'heart-handshake',
            'order' => 250,
            'view_permissions' => ['announcements.view'],
            'actions' => ['announcements.view'],
        ],
        [
            'id' => 'motivation',
            'panel_type' => 'authority',
            'label' => 'Motivasyon',
            'section' => 'communication',
            'href' => '/panel/motivation',
            'icon' => 'sparkles',
            'order' => 260,
            'view_permissions' => ['motivation.view', 'motivation.manage'],
            'actions' => ['motivation.view', 'motivation.manage'],
        ],
        [
            'id' => 'kvkk_forget',
            'panel_type' => 'authority',
            'label' => 'KVKK Unutulma',
            'section' => 'system',
            'href' => '/panel/kvkk-forget',
            'icon' => 'shield-alert',
            'order' => 270,
            'view_permissions' => ['users.update'],
            'actions' => ['users.update'],
        ],
        [
            'id' => 'profile',
            'panel_type' => 'authority',
            'label' => 'Profilim',
            'section' => 'account',
            'href' => '/panel/profile',
            'icon' => 'user-circle',
            'order' => 900,
            'always_visible' => true,
            'view_permissions' => [],
            'actions' => [],
        ],
        [
            'id' => 'participant_dashboard',
            'panel_type' => 'participant',
            'label' => 'Dashboard',
            'section' => 'overview',
            'href' => '/dashboard',
            'icon' => 'layout-dashboard',
            'order' => 10,
            'view_permissions' => ['participant.dashboard.view'],
            'actions' => ['participant.dashboard.view'],
        ],
        [
            'id' => 'participant_projects',
            'panel_type' => 'participant',
            'label' => 'Projelerim',
            'section' => 'learning',
            'href' => '/dashboard/projects',
            'icon' => 'folder-open',
            'order' => 20,
            'view_permissions' => ['participant.projects.view'],
            'actions' => ['participant.projects.view'],
        ],
        [
            'id' => 'participant_programs',
            'panel_type' => 'participant',
            'label' => 'Programlarim',
            'section' => 'learning',
            'href' => '/programs',
            'icon' => 'calendar-days',
            'order' => 30,
            'view_permissions' => ['participant.programs.view'],
            'actions' => ['participant.programs.view', 'participant.qr.use', 'participant.feedback.create'],
        ],
        [
            'id' => 'participant_cv',
            'panel_type' => 'participant',
            'label' => 'Dijital CV',
            'section' => 'profile',
            'href' => '/dashboard/digital-cv',
            'icon' => 'id-card',
            'order' => 40,
            'view_permissions' => ['participant.cv.manage'],
            'actions' => ['participant.cv.manage'],
        ],
        [
            'id' => 'participant_bohca',
            'panel_type' => 'participant',
            'label' => 'Dijital Bohca',
            'section' => 'learning',
            'href' => '/digital-bohca',
            'icon' => 'archive',
            'order' => 50,
            'view_permissions' => ['participant.bohca.view'],
            'actions' => ['participant.bohca.view'],
        ],
        [
            'id' => 'participant_assignments',
            'panel_type' => 'participant',
            'label' => 'Odevler',
            'section' => 'learning',
            'href' => '/assignments',
            'icon' => 'file-check',
            'order' => 60,
            'view_permissions' => ['participant.assignments.view'],
            'actions' => ['participant.assignments.view', 'participant.assignments.submit'],
        ],
        [
            'id' => 'participant_certificates',
            'panel_type' => 'participant',
            'label' => 'Sertifikalar',
            'section' => 'learning',
            'href' => '/certificates',
            'icon' => 'badge-check',
            'order' => 70,
            'view_permissions' => ['participant.certificates.view'],
            'actions' => ['participant.certificates.view'],
        ],
        [
            'id' => 'participant_requests',
            'panel_type' => 'participant',
            'label' => 'Taleplerim',
            'section' => 'support',
            'href' => '/requests',
            'icon' => 'inbox',
            'order' => 80,
            'view_permissions' => ['participant.support.manage'],
            'actions' => ['participant.support.manage'],
        ],
        [
            'id' => 'participant_volunteer',
            'panel_type' => 'participant',
            'label' => 'Gonulluluk',
            'section' => 'community',
            'href' => '/volunteer/opportunities',
            'icon' => 'heart-handshake',
            'order' => 90,
            'view_permissions' => ['participant.volunteer.apply'],
            'actions' => ['participant.volunteer.apply'],
        ],
        [
            'id' => 'participant_kpd',
            'panel_type' => 'participant',
            'label' => 'KPD',
            'section' => 'support',
            'href' => '/kpd/appointments',
            'icon' => 'stethoscope',
            'order' => 100,
            'view_permissions' => ['participant.kpd.view'],
            'actions' => ['participant.kpd.view'],
        ],
        [
            'id' => 'participant_inbox',
            'panel_type' => 'participant',
            'label' => 'Mesajlar',
            'section' => 'communication',
            'href' => '/inbox/messages',
            'icon' => 'mail',
            'order' => 110,
            'view_permissions' => ['participant.inbox.view'],
            'actions' => ['participant.inbox.view'],
        ],
        [
            'id' => 'participant_forum',
            'panel_type' => 'participant',
            'label' => 'Forum',
            'section' => 'community',
            'href' => '/forum/posts',
            'icon' => 'messages-square',
            'order' => 120,
            'view_permissions' => ['participant.forum.view'],
            'actions' => ['participant.forum.view'],
        ],
        [
            'id' => 'alumni_opportunities',
            'panel_type' => 'participant',
            'label' => 'Mezun Firsatlari',
            'section' => 'community',
            'href' => '/alumni-opportunities',
            'icon' => 'briefcase-business',
            'order' => 130,
            'view_permissions' => ['alumni.opportunities.view'],
            'actions' => ['alumni.portal.view', 'alumni.opportunities.view'],
        ],
    ],
];
