<?php

return [
    /**
     * Personel birimi (staffProfile.unit) bu alt dizelerden birini iceriyorsa,
     * manageable proje listesi tum aktif projeler olur (medya / icerik birimi).
     */
    'media_unit_markers' => [
        'medya',
        'media',
        'icerik',
        'content',
    ],

    'role_labels' => [
        'super_admin' => 'Ust Admin',
        'coordinator' => 'Koordinator',
        'staff' => 'Personel',
        'student' => 'Ogrenci',
        'alumni' => 'Mezun',
        'visitor' => 'Ziyaretci',
    ],

    'default_role_permissions' => [
        'super_admin' => '*',
        'coordinator' => [
            'manage projects',
            'manage periods',
            'manage programs',
            'manage applications',
            'manage volunteer',
            'manage financials',
            'manage requests',
            'manage support',
            'manage staff',
            'manage announcements',
            'manage content',
            'manage certificates',
            'manage kpd',
            'manage chatbot',
        ],
        'staff' => [
            'manage programs',
            'manage requests',
            'manage support',
            'manage announcements',
            'manage content',
            'request staff leave',
        ],
        'student' => [],
        'alumni' => [],
        'visitor' => [],
    ],

    'legacy_permissions' => [
        ['name' => 'manage users', 'label' => 'Kullanici Yonetimi', 'group' => 'Yonetim'],
        ['name' => 'manage permission matrix', 'label' => 'Yetki Matrisi', 'group' => 'Yonetim'],
        ['name' => 'manage projects', 'label' => 'Proje Yonetimi', 'group' => 'Projeler'],
        ['name' => 'manage periods', 'label' => 'Donem Yonetimi', 'group' => 'Projeler'],
        ['name' => 'manage programs', 'label' => 'Takvim ve Programlar', 'group' => 'Projeler'],
        ['name' => 'manage applications', 'label' => 'Basvuru Degerlendirme', 'group' => 'Basvurular'],
        ['name' => 'manage volunteer', 'label' => 'Gonulluluk Yonetimi', 'group' => 'Basvurular'],
        ['name' => 'manage financials', 'label' => 'Mali Islemler', 'group' => 'Operasyon'],
        ['name' => 'manage requests', 'label' => 'Talep Yonetimi', 'group' => 'Operasyon'],
        ['name' => 'manage support', 'label' => 'Destek Merkezi', 'group' => 'Operasyon'],
        ['name' => 'manage staff', 'label' => 'Personel Islemleri', 'group' => 'Operasyon'],
        ['name' => 'manage announcements', 'label' => 'Duyuru Gonderimi', 'group' => 'Iletisim'],
        ['name' => 'manage content', 'label' => 'Icerik Yonetimi', 'group' => 'Iletisim'],
        ['name' => 'manage settings', 'label' => 'Sistem Ayarlari', 'group' => 'Sistem'],
        ['name' => 'view logs', 'label' => 'Islem Loglari', 'group' => 'Sistem'],
        ['name' => 'manage certificates', 'label' => 'Sertifika Yonetimi', 'group' => 'Sistem'],
        ['name' => 'manage newsletter', 'label' => 'E-Bulten', 'group' => 'Iletisim'],
        ['name' => 'manage chatbot', 'label' => 'Chatbot', 'group' => 'Sistem'],
        ['name' => 'manage kpd', 'label' => 'KPD Randevulari', 'group' => 'Operasyon'],
        ['name' => 'request staff leave', 'label' => 'Izin Talebi Olusturma', 'group' => 'Operasyon'],
    ],

    'granular_permissions' => [
        'Dashboard' => [
            'dashboard.admin.view',
            'dashboard.coordinator.view',
            'dashboard.staff.view',
        ],
        'Users' => [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.export',
            'users.assign_role',
        ],
        'Permission Matrix' => [
            'permissions.matrix.view',
            'permissions.matrix.update',
            'permissions.user_override.view',
            'permissions.user_override.update',
        ],
        'Projects' => [
            'projects.view',
            'projects.export',
            'projects.content.update',
            'projects.gallery.update',
            'projects.application_form.update',
            'projects.participants.view',
            'projects.participants.manage',
            'projects.alumni.view',
        ],
        'Periods' => [
            'periods.view',
            'periods.create',
            'periods.update',
            'periods.export',
        ],
        'Programs' => [
            'programs.view',
            'programs.attendance.view',
            'programs.attendance.export',
            'programs.create',
            'programs.update',
            'programs.complete',
            'programs.qr.manage',
            'programs.export',
        ],
        'Calendar' => [
            'calendar.view',
            'calendar.assignments.manage',
            'calendar.google.connect',
            'calendar.google.sync',
        ],
        'Applications' => [
            'applications.view',
            'applications.update_status',
            'applications.plan_interview',
            'applications.waitlist.manage',
            'applications.export',
        ],
        'Volunteer' => [
            'volunteer.view',
            'volunteer.manage',
        ],
        'Financials' => [
            'financial.view',
            'financial.create',
            'financial.update',
            'financial.delete',
            'financial.approve',
            'financial.reject',
            'financial.mark_paid',
            'financial.export',
            'financial.invoice.download',
        ],
        'Requests' => [
            'requests.view',
            'requests.create',
            'requests.update_status',
            'requests.upload_response',
            'requests.export',
        ],
        'Support' => [
            'support.view',
            'support.create',
            'support.assign',
            'support.reply',
            'support.close',
            'support.export',
        ],
        'Staff' => [
            'staff.view',
            'staff.update',
            'staff.documents.upload',
            'staff.leave.request',
            'staff.leave.approve',
            'staff.leave.reject',
            'staff.export',
        ],
        'Announcements' => [
            'announcements.view',
            'announcements.create',
            'announcements.update',
            'announcements.delete',
            'announcements.export',
            'announcements.send_sms',
            'announcements.send_email',
        ],
        'Content' => [
            'content.view',
            'content.blog.create',
            'content.blog.update',
            'content.blog.delete',
            'content.blog.export',
            'content.faq.create',
            'content.faq.update',
            'content.faq.delete',
            'content.faq.export',
            'content.site_settings.update',
        ],
        'Settings' => [
            'settings.view',
            'settings.update',
        ],
        'Logs' => [
            'logs.view',
            'logs.export',
        ],
        'Certificates' => [
            'certificates.view',
            'certificates.create',
            'certificates.delete',
            'certificates.export',
        ],
        'Newsletter' => [
            'newsletter.view',
            'newsletter.export',
            'newsletter.manage',
        ],
        'Chatbot' => [
            'chatbot.view',
            'chatbot.manage',
        ],
        'KPD' => [
            'kpd.appointments.view',
            'kpd.appointments.manage',
        ],
    ],

    'legacy_map' => [
        'manage users' => [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.export',
            'users.assign_role',
        ],
        'manage permission matrix' => [
            'permissions.matrix.view',
            'permissions.matrix.update',
            'permissions.user_override.view',
            'permissions.user_override.update',
        ],
        'manage projects' => [
            'projects.view',
            'projects.export',
            'projects.content.update',
            'projects.gallery.update',
            'projects.application_form.update',
            'projects.participants.view',
            'projects.participants.manage',
            'projects.alumni.view',
        ],
        'manage periods' => [
            'periods.view',
            'periods.create',
            'periods.update',
            'periods.export',
        ],
        'manage programs' => [
            'programs.view',
            'programs.attendance.view',
            'programs.attendance.export',
            'programs.create',
            'programs.update',
            'programs.complete',
            'programs.qr.manage',
            'programs.export',
            'calendar.view',
            'calendar.assignments.manage',
            'calendar.google.connect',
            'calendar.google.sync',
        ],
        'manage applications' => [
            'applications.view',
            'applications.update_status',
            'applications.plan_interview',
            'applications.waitlist.manage',
            'applications.export',
        ],
        'manage volunteer' => [
            'volunteer.view',
            'volunteer.manage',
        ],
        'manage financials' => [
            'financial.view',
            'financial.create',
            'financial.update',
            'financial.delete',
            'financial.approve',
            'financial.reject',
            'financial.mark_paid',
            'financial.export',
            'financial.invoice.download',
        ],
        'manage requests' => [
            'requests.view',
            'requests.create',
            'requests.update_status',
            'requests.upload_response',
            'requests.export',
        ],
        'manage support' => [
            'support.view',
            'support.create',
            'support.assign',
            'support.reply',
            'support.close',
            'support.export',
        ],
        'manage staff' => [
            'staff.view',
            'staff.update',
            'staff.documents.upload',
            'staff.leave.request',
            'staff.leave.approve',
            'staff.leave.reject',
            'staff.export',
        ],
        'request staff leave' => [
            'staff.leave.request',
        ],
        'manage announcements' => [
            'announcements.view',
            'announcements.create',
            'announcements.update',
            'announcements.delete',
            'announcements.export',
            'announcements.send_sms',
            'announcements.send_email',
        ],
        'manage content' => [
            'content.view',
            'content.blog.create',
            'content.blog.update',
            'content.blog.delete',
            'content.blog.export',
            'content.faq.create',
            'content.faq.update',
            'content.faq.delete',
            'content.faq.export',
            'content.site_settings.update',
        ],
        'manage settings' => [
            'settings.view',
            'settings.update',
        ],
        'view logs' => [
            'logs.view',
            'logs.export',
        ],
        'manage certificates' => [
            'certificates.view',
            'certificates.create',
            'certificates.delete',
            'certificates.export',
        ],
        'manage newsletter' => [
            'newsletter.view',
            'newsletter.export',
            'newsletter.manage',
        ],
        'manage chatbot' => [
            'chatbot.view',
            'chatbot.manage',
        ],
        'manage kpd' => [
            'kpd.appointments.view',
            'kpd.appointments.manage',
        ],
    ],

    /**
     * Admin panelde hizli scope atamasi icin rol bazli varsayilan template'ler.
     * primary role (users.role) tarafi korunurken custom roller icin de referans olarak kullanilir.
     */
    'scope_templates' => [
        'global_admin' => [
            'label' => 'Global (tum projeler)',
            'scope_type' => 'all',
            'scope_payload' => [],
        ],
        'project_owner' => [
            'label' => 'Own Projects',
            'scope_type' => 'own_projects',
            'scope_payload' => ['project_ids' => []],
        ],
        'assigned_projects' => [
            'label' => 'Assigned Projects',
            'scope_type' => 'assigned_projects',
            'scope_payload' => ['project_ids' => []],
        ],
        'selected_projects' => [
            'label' => 'Selected Projects',
            'scope_type' => 'selected_projects',
            'scope_payload' => ['project_ids' => []],
        ],
        'own_unit' => [
            'label' => 'Own Unit',
            'scope_type' => 'own_unit',
            'scope_payload' => ['unit' => null],
        ],
    ],
];
