<?php

return [
    /**
     * Personel birimi (staffProfile.unit) bu alt dizelerden birini iceriyorsa,
     * manageable proje listesi tum aktif projeler olur (medya / icerik birimi).
     */
    'media_unit_markers' => [
        'medya',
        'media',
        'icerik',
        'content',
    ],

    /**
     * Takvimde etkinlik cakismalarini gorebilmek icin coordinator/personel tum projeleri gorebilir.
     * false yapilirse calendar.view scope kurali birebir uygulanir.
     */
    'calendar_cross_project_view_for_staff_coordinator' => true,

    'role_labels' => [
        'super_admin' => 'Ust Admin',
        'coordinator' => 'Koordinator',
        'staff' => 'Personel',
        'student' => 'Ogrenci',
        'alumni' => 'Mezun',
        'visitor' => 'Ziyaretci',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authorization management boundaries
    |--------------------------------------------------------------------------
    |
    | Coordinator/staff icin asagidaki gruplar organizasyon birimi isi sayilir.
    | Enforce modunda bu izinlerin etkili kaynagi global rol matrisi degil,
    | coordination_unit_permission_rules tablosudur. Liste tek merkezde tutularak
    | API korumasi ve admin arayuzu ayni siniflandirmayi kullanir.
    |
    */
    'coordination_unit_business_groups' => [
        'Dashboard',
        'Projects',
        'Project Special Modules',
        'Digital Bohca',
        'Assignments',
        'Periods',
        'Programs',
        'Calendar',
        'Applications',
        'Volunteer',
        'Financials',
        'Requests',
        'Support',
        'Staff',
        'Announcements',
        'Authority Communication',
        'Content',
        'Certificates',
        'KPD',
    ],

    'coordination_unit_business_roles' => [
        'coordinator',
        'staff',
    ],

    /*
     * Varsayilan false degeri mevcut rol izinlerini korur. Sadece bilincli bir
     * yeniden kurulumda true yapilarak sistem rol varsayilanlari tekrar yazilir.
     */
    'reset_default_role_permissions' => env('PERMISSION_SEEDER_RESET_DEFAULTS', false),

    'default_role_permissions' => [
        'super_admin' => '*',
        'coordinator' => [
            'dashboard.coordinator.view',
            'manage projects',
            'manage periods',
            'manage programs',
            'manage applications',
            'manage volunteer',
            'manage financials',
            'manage requests',
            'manage support',
            'support.update',
            'support.reopen',
            'manage staff',
            'manage announcements',
            'manage content',
            'manage certificates',
            'manage kpd',
            'manage chatbot',
        ],
        'staff' => [
            'dashboard.staff.view',
            'manage programs',
            'manage requests',
            'manage support',
            'manage announcements',
            'manage content',
            'request staff leave',
        ],
        'student' => [
            'participant.dashboard.view',
            'participant.projects.view',
            'participant.programs.view',
            'participant.qr.use',
            'participant.feedback.create',
            'participant.cv.manage',
            'participant.bohca.view',
            'participant.assignments.view',
            'participant.assignments.submit',
            'participant.certificates.view',
            'participant.volunteer.apply',
            'participant.support.manage',
            'participant.profile.manage',
            'participant.inbox.view',
            'participant.forum.view',
            'participant.kpd.view',
            'alumni.opportunities.view',
        ],
        'alumni' => [
            'participant.dashboard.view',
            'participant.projects.view',
            'participant.programs.view',
            'participant.qr.use',
            'participant.feedback.create',
            'participant.cv.manage',
            'participant.bohca.view',
            'participant.assignments.view',
            'participant.assignments.submit',
            'participant.certificates.view',
            'participant.volunteer.apply',
            'participant.support.manage',
            'participant.profile.manage',
            'participant.inbox.view',
            'participant.forum.view',
            'participant.kpd.view',
            'alumni.portal.view',
            'alumni.opportunities.view',
        ],
        'visitor' => [],
    ],

    'legacy_permissions' => [
        ['name' => 'manage users', 'label' => 'Kullanici Yonetimi', 'group' => 'Yonetim'],
        ['name' => 'manage permission matrix', 'label' => 'Yetki Matrisi', 'group' => 'Yonetim'],
        ['name' => 'manage projects', 'label' => 'Proje Yonetimi', 'group' => 'Projeler'],
        ['name' => 'manage periods', 'label' => 'Donem Yonetimi', 'group' => 'Projeler'],
        ['name' => 'manage programs', 'label' => 'Takvim ve Programlar', 'group' => 'Projeler'],
        ['name' => 'manage applications', 'label' => 'Basvuru Degerlendirme', 'group' => 'Basvurular'],
        ['name' => 'manage volunteer', 'label' => 'Gonulluluk Yonetimi', 'group' => 'Basvurular'],
        ['name' => 'manage financials', 'label' => 'Mali Islemler', 'group' => 'Operasyon'],
        ['name' => 'manage requests', 'label' => 'Talep Yonetimi', 'group' => 'Operasyon'],
        ['name' => 'manage support', 'label' => 'Destek Merkezi', 'group' => 'Operasyon'],
        ['name' => 'manage staff', 'label' => 'Personel Islemleri', 'group' => 'Operasyon'],
        ['name' => 'manage trainers', 'label' => 'Egitmen Bilgileri', 'group' => 'Yonetim'],
        ['name' => 'manage announcements', 'label' => 'Duyuru Gonderimi', 'group' => 'Iletisim'],
        ['name' => 'manage content', 'label' => 'Icerik Yonetimi', 'group' => 'Iletisim'],
        ['name' => 'manage settings', 'label' => 'Sistem Ayarlari', 'group' => 'Sistem'],
        ['name' => 'view logs', 'label' => 'Islem Loglari', 'group' => 'Sistem'],
        ['name' => 'manage certificates', 'label' => 'Sertifika Yonetimi', 'group' => 'Sistem'],
        ['name' => 'manage newsletter', 'label' => 'E-Bulten', 'group' => 'Iletisim'],
        ['name' => 'manage chatbot', 'label' => 'Chatbot', 'group' => 'Sistem'],
        ['name' => 'manage kpd', 'label' => 'KPD Randevulari', 'group' => 'Operasyon'],
        ['name' => 'request staff leave', 'label' => 'Izin Talebi Olusturma', 'group' => 'Operasyon'],
    ],

    'granular_permissions' => [
        'Dashboard' => [
            'dashboard.admin.view',
            'dashboard.coordinator.view',
            'dashboard.staff.view',
        ],
        'Users' => [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.export',
            'users.assign_role',
        ],
        'Permission Matrix' => [
            'permissions.matrix.view',
            'permissions.matrix.update',
            'permissions.user_override.view',
            'permissions.user_override.update',
        ],
        'Coordination Units' => [
            'coordination_units.view',
            'coordination_units.manage',
            'coordination_units.memberships.manage',
            'coordination_units.responsibilities.manage',
            'coordination_units.permissions.view',
            'coordination_units.permissions.manage',
            'coordination_units.authorization.preview',
        ],
        'Projects' => [
            'projects.view',
            'projects.export',
            'projects.content.update',
            'projects.public_content.view',
            'projects.public_content.update',
            'projects.gallery.update',
            'projects.application_form.update',
            'projects.participants.view',
            'projects.participants.manage',
            'projects.alumni.view',
            'projects.student_cv.view',
            'projects.attendance.view',
            'projects.attendance.export',
        ],
        'Project Special Modules' => [
            'projects.internships.view',
            'projects.internships.manage',
            'projects.mentors.view',
            'projects.mentors.manage',
            'projects.eurodesk.view',
            'projects.eurodesk.manage',
            'projects.rewards.view',
            'projects.rewards.manage',
        ],
        'Digital Bohca' => [
            'digital_bohca.view',
            'digital_bohca.create',
            'digital_bohca.delete',
        ],
        'Assignments' => [
            'assignments.view',
            'assignments.create',
            'assignments.update',
            'assignments.delete',
            'assignments.submissions.view',
            'assignments.submissions.review',
        ],
        'Periods' => [
            'periods.view',
            'periods.create',
            'periods.update',
            'periods.activate',
            'periods.closing.start',
            'periods.closing.cancel',
            'periods.complete',
            'periods.reopen',
            'periods.cancel',
            'periods.archive.update',
            'periods.archive.correct',
            'periods.archive.verify',
            'periods.export',
        ],
        'Programs' => [
            'programs.view',
            'programs.community_event.view',
            'programs.community_event.create',
            'programs.community_event.update',
            'programs.community_event.attendance.view',
            'programs.community_event.attendance.manage',
            'programs.community_event.attendance.export',
            'programs.logistics.view',
            'programs.logistics.update',
            'programs.attendance.view',
            'programs.attendance.manage',
            'programs.attendance.export',
            'programs.create',
            'programs.update',
            'programs.media.upload',
            'programs.complete',
            'programs.qr.manage',
            'programs.export',
        ],
        'Calendar' => [
            'calendar.view',
            'calendar.export',
            'calendar.assignments.manage',
            'calendar.meetings.create',
            'calendar.meetings.manage',
            'calendar.google.connect',
            'calendar.google.sync',
        ],
        'Applications' => [
            'applications.view',
            'applications.intake.view',
            'applications.intake.manage',
            'applications.update_status',
            'applications.plan_interview',
            'applications.waitlist.manage',
            'applications.export',
        ],
        'Volunteer' => [
            'volunteer.view',
            'volunteer.manage',
        ],
        'Financials' => [
            'financial.view',
            'financial.create',
            'financial.update',
            'financial.delete',
            'financial.approve',
            'financial.reject',
            'financial.mark_paid',
            'financial.export',
            'financial.invoice.download',
        ],
        'Requests' => [
            'requests.view',
            'requests.create',
            'requests.update_status',
            'requests.upload_response',
            'requests.export',
        ],
        'Support' => [
            'support.view',
            'support.create',
            'support.assign',
            'support.reply',
            'support.close',
            'support.update',
            'support.reopen',
            'support.export',
        ],
        'Staff' => [
            'staff.view',
            'staff.update',
            'staff.documents.upload',
            'staff.leave.request',
            'staff.leave.approve',
            'staff.leave.reject',
            'staff.export',
        ],
        'Trainers' => [
            'trainers.view',
            'trainers.create',
            'trainers.update',
            'trainers.delete',
            'trainers.comment',
            'trainers.email',
            'trainers.export',
        ],
        'Announcements' => [
            'announcements.view',
            'announcements.create',
            'announcements.update',
            'announcements.delete',
            'announcements.export',
            'announcements.send_sms',
            'announcements.send_email',
        ],
        'Authority Communication' => [
            'inbox.view',
            'alumni_opportunities.view',
            'alumni_opportunities.manage',
            'forum.view',
            'forum.moderate',
        ],
        'Content' => [
            'content.view',
            'content.blog.create',
            'content.blog.update',
            'content.blog.publish',
            'content.blog.delete',
            'content.blog.export',
            'content.faq.create',
            'content.faq.update',
            'content.faq.delete',
            'content.faq.export',
            'content.site_settings.update',
            'content.personality.view',
            'content.personality.manage',
            'motivation.view',
            'motivation.manage',
        ],
        'Settings' => [
            'settings.view',
            'settings.update',
        ],
        'Logs' => [
            'logs.view',
            'logs.export',
        ],
        'Certificates' => [
            'certificates.view',
            'certificates.create',
            'certificates.delete',
            'certificates.export',
        ],
        'Newsletter' => [
            'newsletter.view',
            'newsletter.export',
            'newsletter.manage',
        ],
        'Chatbot' => [
            'chatbot.view',
            'chatbot.manage',
        ],
        'Participant Portal' => [
            'participant.dashboard.view',
            'participant.projects.view',
            'participant.programs.view',
            'participant.qr.use',
            'participant.feedback.create',
            'participant.cv.manage',
            'participant.bohca.view',
            'participant.assignments.view',
            'participant.assignments.submit',
            'participant.certificates.view',
            'participant.volunteer.apply',
            'participant.support.manage',
            'participant.profile.manage',
            'participant.inbox.view',
            'participant.forum.view',
            'participant.kpd.view',
        ],
        'Alumni Portal' => [
            'alumni.portal.view',
            'alumni.opportunities.view',
        ],
        'KPD' => [
            'kpd.appointments.view',
            'kpd.appointments.manage',
            'kpd.reports.view',
            'kpd.reports.create',
            'kpd.reports.delete',
        ],
    ],

    'legacy_map' => [
        'manage users' => [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.export',
            'users.assign_role',
        ],
        'manage permission matrix' => [
            'permissions.matrix.view',
            'permissions.matrix.update',
            'permissions.user_override.view',
            'permissions.user_override.update',
        ],
        'manage projects' => [
            'projects.view',
            'projects.export',
            'projects.content.update',
            'projects.public_content.view',
            'projects.public_content.update',
            'projects.gallery.update',
            'projects.application_form.update',
            'projects.participants.view',
            'projects.participants.manage',
            'projects.alumni.view',
            'projects.student_cv.view',
            'projects.attendance.view',
            'projects.attendance.export',
            'projects.internships.view',
            'projects.internships.manage',
            'projects.mentors.view',
            'projects.mentors.manage',
            'projects.eurodesk.view',
            'projects.eurodesk.manage',
            'projects.rewards.view',
            'projects.rewards.manage',
            'digital_bohca.view',
            'digital_bohca.create',
            'digital_bohca.delete',
            'assignments.view',
            'assignments.create',
            'assignments.update',
            'assignments.delete',
            'assignments.submissions.view',
            'assignments.submissions.review',
        ],
        'manage periods' => [
            'periods.view',
            'periods.create',
            'periods.update',
            'periods.activate',
            'periods.closing.start',
            'periods.closing.cancel',
            'periods.complete',
            'periods.cancel',
            'periods.archive.verify',
            'periods.export',
        ],
        'manage programs' => [
            'programs.view',
            'programs.community_event.view',
            'programs.community_event.create',
            'programs.community_event.update',
            'programs.community_event.attendance.view',
            'programs.community_event.attendance.manage',
            'programs.community_event.attendance.export',
            'programs.logistics.view',
            'programs.logistics.update',
            'programs.attendance.view',
            'programs.attendance.manage',
            'programs.attendance.export',
            'programs.create',
            'programs.update',
            'programs.media.upload',
            'programs.complete',
            'programs.qr.manage',
            'programs.export',
            'calendar.view',
            'calendar.export',
            'calendar.assignments.manage',
            'calendar.meetings.create',
            'calendar.meetings.manage',
            'calendar.google.connect',
            'calendar.google.sync',
        ],
        'manage applications' => [
            'applications.view',
            'applications.intake.view',
            'applications.intake.manage',
            'applications.update_status',
            'applications.plan_interview',
            'applications.waitlist.manage',
            'applications.export',
        ],
        'manage volunteer' => [
            'volunteer.view',
            'volunteer.manage',
        ],
        'manage financials' => [
            'financial.view',
            'financial.create',
            'financial.update',
            'financial.delete',
            'financial.approve',
            'financial.reject',
            'financial.mark_paid',
            'financial.export',
            'financial.invoice.download',
        ],
        'manage requests' => [
            'requests.view',
            'requests.create',
            'requests.update_status',
            'requests.upload_response',
            'requests.export',
        ],
        'manage support' => [
            'support.view',
            'support.create',
            'support.assign',
            'support.reply',
            'support.close',
            'support.export',
        ],
        'manage staff' => [
            'staff.view',
            'staff.update',
            'staff.documents.upload',
            'staff.leave.request',
            'staff.leave.approve',
            'staff.leave.reject',
            'staff.export',
        ],
        'manage trainers' => [
            'trainers.view',
            'trainers.create',
            'trainers.update',
            'trainers.delete',
            'trainers.comment',
            'trainers.email',
            'trainers.export',
        ],
        'request staff leave' => [
            'staff.leave.request',
        ],
        'manage announcements' => [
            'announcements.view',
            'announcements.create',
            'announcements.update',
            'announcements.delete',
            'announcements.export',
            'announcements.send_sms',
            'announcements.send_email',
        ],
        'manage content' => [
            'content.view',
            'content.blog.create',
            'content.blog.update',
            'content.blog.publish',
            'content.blog.delete',
            'content.blog.export',
            'content.faq.create',
            'content.faq.update',
            'content.faq.delete',
            'content.faq.export',
            'content.site_settings.update',
            'content.personality.view',
            'content.personality.manage',
            'motivation.view',
            'motivation.manage',
        ],
        'manage settings' => [
            'settings.view',
            'settings.update',
            'content.personality.view',
            'content.personality.manage',
            'motivation.view',
            'motivation.manage',
        ],
        'view logs' => [
            'logs.view',
            'logs.export',
        ],
        'manage certificates' => [
            'certificates.view',
            'certificates.create',
            'certificates.delete',
            'certificates.export',
        ],
        'manage newsletter' => [
            'newsletter.view',
            'newsletter.export',
            'newsletter.manage',
        ],
        'manage chatbot' => [
            'chatbot.view',
            'chatbot.manage',
        ],
        'manage kpd' => [
            'kpd.appointments.view',
            'kpd.appointments.manage',
            'kpd.reports.view',
            'kpd.reports.create',
            'kpd.reports.delete',
        ],
    ],

    /**
     * Admin panelde hizli scope atamasi icin rol bazli varsayilan template'ler.
     * primary role (users.role) tarafi korunurken custom roller icin de referans olarak kullanilir.
     */
    'scope_templates' => [
        'global_admin' => [
            'label' => 'Global (tum projeler)',
            'scope_type' => 'all',
            'scope_payload' => [],
        ],
        'project_owner' => [
            'label' => 'Own Projects',
            'scope_type' => 'own_projects',
            'scope_payload' => ['project_ids' => []],
        ],
        'assigned_projects' => [
            'label' => 'Assigned Projects',
            'scope_type' => 'assigned_projects',
            'scope_payload' => ['project_ids' => []],
        ],
        'selected_projects' => [
            'label' => 'Selected Projects',
            'scope_type' => 'selected_projects',
            'scope_payload' => ['project_ids' => []],
        ],
        'own_unit' => [
            'label' => 'Own Unit',
            'scope_type' => 'own_unit',
            'scope_payload' => ['unit' => null],
        ],
    ],
];
